//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.21 at 08:21:51 обнГ CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.leuville.com/commande")
package ex7;
